### ISSUE TITLE
Tensorflow 2 support (?)

### ISSUE THREAD

**Issue by masc-it** [microsoft/tensorflow-directml#107]
Are you planning to support tensorflow 2 in the near future? 
It would be awesome, in particular for unlucky AMD GPU owners (like me..)

**Comment by jstoecker** [comment]
We're considering a few options with respect to TF2.

Our focus right now is solid support of TF 1.15: good operator coverage, performance, and reliability. There's still quite a bit of work here, especially with performance, so we don't want to jump into multiple versions of TF until we have a good non-preview release of 1.15.

A huge amount of work goes into supporting various operators, and we believe much of this effort will be applicable in newer versions of TF as well. However, the device runtime (memory allocation, copying tensors, inter-device communication, execution strategies, etc.) is likely to be a bit different. It's an option for us to support and build TF 1.15 and 2.x out of this fork, but ideally we want to have the DML backend integrate with the main repository at some point. There are different proposals for how this might work (e.g. composable device backends), so we'll have to weigh the options once we're closer to wrapping up 1.15. 

Some more background here: https://github.com/tensorflow/community/pull/243

**Comment by masc-it** [comment]
@jstoecker   that's great, really appreciate your efforts! When you'll be able to get this in the main tf branch.. that's going to be awesome! I'm saying this because I've randomly discovered DirectML after weeks of useless attempts with other solutions.. and the [setup ](https://docs.microsoft.com/en-us/windows/win32/direct3d12/gpu-tensorflow-windows) went so smooth (apart from fixing numpy version) that I couldn't believe my eyes! 

btw, have you ever consider to publish a beta branch with your ongoing tf2 integration? The community might help in the process!

**Comment by jstoecker** [comment]
Thanks masc-it, we appreciate that a lot!

There's a reason we're keeping the default branch for this fork separate from master (you may have noticed it's `directml` instead of `master`): we may have multiple versions of TF here at some point. :) We don't know how likely that is just yet, since ideally future work will be done upstream or in a way that's compatible with upstream, but it's a possibility we've considered. It's just too early to create that branch since we can't maintain it yet!

**Comment by wchao1115** [comment]
@masc-it Does it matter to you which version of TF2 this support should be in? Given that 2.4 is the latest it seems most economic to target those instead of, say, 2.2.

**Comment by masc-it** [comment]
@wchao1115  Are you even asking me?! Sure that'd be awesome! :D

**Comment by KawabataLemon** [comment]
Is there any update regarding this issue? 
I'm very looking forward to use directml in tf2.x.
