### ISSUE TITLE
Latest TensorFlow-DirectML C API package

### ISSUE THREAD

**Issue by boyedarat** [microsoft/tensorflow-directml#135]
Would it be possible to release a C API package each time the Python packages are released? I don't have access to the Windows Insider SDKs and have not been successful in building it from source.

**Comment by jstoecker** [comment]
It's a good question. 

In future releases, one possibility is that we publish a native NuGet package containing the TensorFlow-DirectML C library to nuget.org, which could in turn depend on the matching DirectML redistributable package. This would make integration with VS-based projects quite easy, at least, and it's not too difficult to add NuGet hooks to CMake or Bazel projects either.

For now,  I've added the packages under the assets of the [last release](https://github.com/microsoft/tensorflow-directml/releases/tag/v1.15.4.dev201216). I've included the matching DirectML library in the package as well; so long as you keep DirectML.<SHA>.dll next to tensorflow.dll the runtime should find it without any extra work on your end.

**Comment by sritharans** [comment]
> It's a good question.
> 
> In future releases, one possibility is that we publish a native NuGet package containing the TensorFlow-DirectML C library to nuget.org, which could in turn depend on the matching DirectML redistributable package. This would make integration with VS-based projects quite easy, at least, and it's not too difficult to add NuGet hooks to CMake or Bazel projects either.
> 
> For now, I've added the packages under the assets of the [last release](https://github.com/microsoft/tensorflow-directml/releases/tag/v1.15.4.dev201216). I've included the matching DirectML library in the package as well; so long as you keep DirectML..dll next to tensorflow.dll the runtime should find it without any extra work on your end.

Just wanted to thank you very much for creating this package. It has been working well so far on with the exception of the following minor errors on startup:
```
2021-01-05 21:24:31.761912: E tensorflow/core/framework/op_kernel.cc:1575] OpKernel ('op: "ApplyKerasMomentum" device_type: "DML" constraint { name: "T" allowed_values { list { type: DT_FLOAT } } }') for unknown op: ApplyKerasMomentum
2021-01-05 21:24:31.762606: E tensorflow/core/framework/op_kernel.cc:1575] OpKernel ('op: "ApplyKerasMomentum" device_type: "DML" constraint { name: "T" allowed_values { list { type: DT_HALF } } }') for unknown op: ApplyKerasMomentum

```
Please do continue to release new pre-built C API packages. Thanks!

**Comment by jstoecker** [comment]
@sritharans thanks for reporting this bug. It looks like one of our (internal) helper kernels is registered but doesn't have an associated opdef. We'll make sure to fix this.

It's good to hear that the C API packages are useful, so we'll make sure to publish them along with pypi. :)

**Comment by boyedarat** [comment]
@jstoecker When is the next update coming? Would we be able to build the upcoming C API package using the [open DirectX headers](https://github.com/microsoft/DirectX-Headers)?

Noticed some info about an upcoming TF 2.4 support in [this issue](https://github.com/microsoft/tensorflow-directml/issues/107). Is this planned for the upcoming build?

Thanks for the great work.

**Comment by jstoecker** [comment]
@boyedarat the next TF release will require DirectML 1.5, which includes some important performance improvements and a few new APIs. We expect to release DML 1.5 and a new version of TF around the end of March / early April. TF 2.x investigation will likely start shortly after the March release.

We do plan to switch over to the open DX headers! This should make it easier to build without requiring an insider SDK. :)

**Comment by ericstj** [comment]
> it's good to hear that the C API packages are useful, so we'll make sure to publish them along with pypi. :)

C-API package could be interesting for use by ML.NET https://github.com/dotnet/machinelearning/issues/5240
Might also be interesting for SciSharp: https://scisharp.github.io/SciSharp/ cc @Oceania2018

Consider publishing them in a way that's consumable by NuGet.

**Comment by jstoecker** [comment]
Latest release is out now: https://github.com/microsoft/tensorflow-directml/releases/tag/v1.15.5.dev210422

We probably will look into making this a native nuget at some point! Perhaps for the v1 release.
