### ISSUE TITLE
Does this mitigate the requirement of installing CuDNN?

### ISSUE THREAD

**Issue by roychowdhuryrohit-dev** [microsoft/tensorflow-directml#17]
If I use DirectML, do I still need to install the CUDA libraries? What about support for upcoming RDNA2 AMD GPUs?

**Comment by jstoecker** [comment]
There is no need to install CUDA or cuDNN when using DirectML. 

All DirectX 12-capable GPUs support DirectML, and that definitely includes the upcoming RDNA2 AMD GPUs.

**Comment by roychowdhuryrohit-dev** [comment]
That’s a pretty big news, thanks for the platform-agnostic support. This solves lot of existing problems that have been prevalent in local AI training ecosystem. I hope this is also true for WSL atleast.

**Comment by jstoecker** [comment]
Cross-vendor support is fundamental to the DirectX platform as a whole, and that includes both Windows and WSL! We have preview drivers for AMD, Intel, and NVIDIA (see [this page](https://docs.microsoft.com/en-us/windows/win32/direct3d12/gpu-tensorflow-wsl)).

**Comment by roychowdhuryrohit-dev** [comment]
I hope everyone(developers, researchers, students) start migrating to DirectML soon. 👍
