### ISSUE TITLE
'protobuf.bzl no such package' error while compiling directML from source

### ISSUE THREAD

**Issue by masc-it** [microsoft/tensorflow-directml#198]
Hello, I'm trying to compile tf-directml from source but I get weird errors about 'protobuf.bzl'. 

I've followed your suggested build-guide and tensorflow's one. I've run the configure.py and build command using msys2 on Windows 10.

Below is the full log of the run, any hints?

<pre><code> python build.py
Extracting Bazel installation...
Starting local Bazel server and connecting to it...
INFO: Options provided by the client:
  Inherited 'common' options: --isatty=0 --terminal_columns=80
INFO: Options provided by the client:
  'build' options: --python_path=C:/Users/masc9/AppData/Local/Programs/Python/Python38/python.exe
INFO: Reading rc options for 'build' from d:\projects\tensorflow-directml\.bazelrc:
  'build' options: --apple_platform_type=macos --define framework_shared_object=true --define open_source_build=true --define=use_fast_cpp_protos=true --define=allow_oversize_protos=true --spawn_strategy=standalone -c opt --announce_rc --define=grpc_no_ares=true --define=PREFIX=/usr --define=LIBDIR=$(PREFIX)/lib --define=INCLUDEDIR=$(PREFIX)/include --copt=-w --config=v1
INFO: Reading rc options for 'build' from d:\projects\tensorflow-directml\.tf_configure.bazelrc:
  'build' options: --action_env PYTHON_BIN_PATH=C:/Users/masc9/AppData/Local/Programs/Python/Python38/python.exe --action_env PYTHON_LIB_PATH=C:/Users/masc9/AppData/Local/Programs/Python/Python38/lib/site-packages --python_path=C:/Users/masc9/AppData/Local/Programs/Python/Python38/python.exe --config=xla --config monolithic --copt=-w --host_copt=-w --copt=-DWIN32_LEAN_AND_MEAN --host_copt=-DWIN32_LEAN_AND_MEAN --copt=-DNOGDI --host_copt=-DNOGDI --verbose_failures --distinct_host_configuration=false --define=override_eigen_strong_inline=true --action_env TF_CONFIGURE_IOS=0
INFO: Found applicable config definition build:v1 in file d:\projects\tensorflow-directml\.bazelrc: --define=tf_api_version=1 --action_env=TF2_BEHAVIOR=0
INFO: Found applicable config definition build:xla in file d:\projects\tensorflow-directml\.bazelrc: --action_env=TF_ENABLE_XLA=1 --define=with_xla_support=true
INFO: Found applicable config definition build:xla in file d:\projects\tensorflow-directml\.tf_configure.bazelrc: --define with_xla_support=true
INFO: Found applicable config definition build:monolithic in file d:\projects\tensorflow-directml\.bazelrc: --define framework_shared_object=false
INFO: Found applicable config definition build:opt in file d:\projects\tensorflow-directml\.tf_configure.bazelrc: --copt=/arch:AVX --define with_default_optimizations=true
INFO: Found applicable config definition build:dml in file d:\projects\tensorflow-directml\.bazelrc: --define=using_dml=true --copt -DTENSORFLOW_USE_DIRECTML
Loading:
Loading: 0 packages loaded
Loading: 0 packages loaded
Loading: 0 packages loaded
Loading: 0 packages loaded
DEBUG: Rule 'io_bazel_rules_docker' indicated that a canonical reproducible form can be obtained by modifying arguments shallow_since = "1556410077 -0400"
Loading: 0 packages loaded
Loading: 0 packages loaded
Loading: 0 packages loaded
Loading: 0 packages loaded
Loading: 0 packages loaded
Analyzing: target //tensorflow/tools/pip_package:build_pip_package (1 packages loaded, 0 targets configured)
ERROR: D:/projects/tensorflow-directml/tensorflow/tools/pip_package/BUILD:233:1: error loading package 'tensorflow': in D:/projects/tensorflow-directml/tensorflow/core/platform/default/build_config.bzl: Encountered error while reading extension file 'protobuf.bzl': no such package '@com_google_protobuf//': Traceback (most recent call last):
        File "D:/projects/tensorflow-directml/third_party/repo.bzl", line 104
                _apply_patch(ctx, ctx.attr.patch_file)
        File "D:/projects/tensorflow-directml/third_party/repo.bzl", line 71, in _apply_patch
                _execute_and_check_ret_code(ctx, cmd)
        File "D:/projects/tensorflow-directml/third_party/repo.bzl", line 52, in _execute_and_check_ret_code
                fail("Non-zero return code({1}) when ...))
Non-zero return code(127) when executing 'C:\msys64\usr\bin\bash.exe -l -c "patch" "-p1" "-d" "D:/projects/dml_build/3t5smh3m/external/com_google_protobuf" "-i" "D:/projects/tensorflow-directml/third_party/protobuf/protobuf.patch"':
Stdout:
Stderr: /usr/bin/bash: line 1: patch: command not found
 and referenced by '//tensorflow/tools/pip_package:build_pip_package'
ERROR: Analysis of target '//tensorflow/tools/pip_package:build_pip_package' failed; build aborted: error loading package 'tensorflow': in D:/projects/tensorflow-directml/tensorflow/core/platform/default/build_config.bzl: Encountered error while reading extension file 'protobuf.bzl': no such package '@com_google_protobuf//': Traceback (most recent call last):
        File "D:/projects/tensorflow-directml/third_party/repo.bzl", line 104
                _apply_patch(ctx, ctx.attr.patch_file)
        File "D:/projects/tensorflow-directml/third_party/repo.bzl", line 71, in _apply_patch
                _execute_and_check_ret_code(ctx, cmd)
        File "D:/projects/tensorflow-directml/third_party/repo.bzl", line 52, in _execute_and_check_ret_code
                fail("Non-zero return code({1}) when ...))
Non-zero return code(127) when executing 'C:\msys64\usr\bin\bash.exe -l -c "patch" "-p1" "-d" "D:/projects/dml_build/3t5smh3m/external/com_google_protobuf" "-i" "D:/projects/tensorflow-directml/third_party/protobuf/protobuf.patch"':
Stdout:
Stderr: /usr/bin/bash: line 1: patch: command not found
INFO: Elapsed time: 15.738s
INFO: 0 processes.
FAILED: Build did NOT complete successfully (4 packages loaded, 0 targets configured)
FAILED: Build did NOT complete successfully (4 packages loaded, 0 targets configured)
Traceback (most recent call last):
  File "build.py", line 371, in <module>
    main()
  File "build.py", line 358, in main
    build(args)
  File "build.py", line 221, in build
    subprocess.run(" ".join(cl), shell=True, check=True)
  File "C:\Users\masc9\AppData\Local\Programs\Python\Python38\lib\subprocess.py", line 512, in run
    raise CalledProcessError(retcode, process.args,
subprocess.CalledProcessError: Command 'bazel --output_user_root=D:\Projects\tensorflow-directml\..\dml_build build --config=opt --config=dml --strip never --copt /wd4716 --copt /Z7 --copt /FS --linkopt /DEBUG:FASTLINK //tensorflow/tools/pip_package:build_pip_package' returned non-zero exit status 1.
</code></pre>

**Comment by jstoecker** [comment]
This looks like the problem:

```
Non-zero return code(127) when executing 'C:\msys64\usr\bin\bash.exe -l -c "patch" "-p1" "-d" "D:/projects/dml_build/3t5smh3m/external/com_google_protobuf" "-i" "D:/projects/tensorflow-directml/third_party/protobuf/protobuf.patch"':
Stdout:
Stderr: /usr/bin/bash: line 1: patch: command not found
```

You may have missed installing the `patch` & `unzip` packages inside msys. Try running this and rebuilding:

```
S:\msys64\usr\bin\pacman.exe -S git patch unzip
```

Let me know if you run into other issues and I'll try to help out, but my availability will be spotty over the next few weeks so it may take some time to reply.
