### ISSUE TITLE
[Feature Request] DirectML as Pluggable device for TensorFlow

### ISSUE THREAD

**Issue by HighCWu** [microsoft/tensorflow-directml#309]
In the latest version of Tensorflow ([v2.5.0](https://github.com/tensorflow/tensorflow/releases/tag/v2.5.0)), PluggableDevice support has been added.
At the beginning, I paid attention to your dml implementation and apple's [apple/tensorflow_macos](https://github.com/apple/tensorflow_macos) implementation at the same time. Recently I suddenly discovered that their repo has been archived. After checking carefully, I know that they directly use PluggableDevice to make tensorflow run on metal.
This plug-in approach, I think, should also be very suitable for directml.

**Comment by PatriceVignola** [comment]
Hi @HighCWu

This repository is dedicated to TensorFlow 1.15, which doesn't have PluggableDevice support. A PluggableDevice plugin for TensorFlow 2.x is our very next step though and we already started investigating and working on it, so stay tuned!

**Comment by HighCWu** [comment]
Great, I am looking forward to it.

**Comment by zhmlcg** [comment]
I hope I can contribute to the development of tensorflow2-directml so that it will be released sooner. But I would only mess things up thanks to my poor background ;-)

**Comment by marunguy** [comment]
Is there any progress?

**Comment by PatriceVignola** [comment]
There's been a lot of progress :)

We cannot say exactly when, but we're planning the release of a preview package very soon. I'll reply to this issue once it's released!

**Comment by oscarbg** [comment]
+1 to be notified :-)

**Comment by value808** [comment]
+1 to be notified myself. thanks, this is gold!

**Comment by Kwinpeng** [comment]
+1 to be notified.

**Comment by rjdyk** [comment]
DirectML is officially available as a PluggableDevice for TensorFlow🎉!

Our preview package can be found on [PyPI](https://pypi.org/project/tensorflow-directml-plugin/) and the project is [fully open-source](https://github.com/microsoft/tensorflow-directml-plugin).

This is the initial preview of the DML pluggable device so please leave any feedback or suggestions on GitHub.

**Comment by HighCWu** [comment]
Great, I will try it.
