### ISSUE TITLE
AMD APU support?

### ISSUE THREAD

**Issue by zabique** [microsoft/tensorflow-directml#378]
Hi,

Will there be support for AMD APUs?  I would like to test Steam deck performance however no GPU detected. Thanks
![image_2022-07-10_123801187](https://user-images.githubusercontent.com/58276510/178143239-eb4b42b2-1811-400d-8128-080078d1b668.png)

**Comment by PatriceVignola** [comment]
We do support AMD GPUs, but `tensorflow-directml` doesn't work on native Linux; only Windows and WSL. This is because it depends on D3D12 and DirectML, which are not available for native Linux.

**Comment by zabique** [comment]
> We do support AMD GPUs, but `tensorflow-directml` doesn't work on native Linux; only Windows and WSL. This is because it depends on D3D12 and DirectML, which are not available for native Linux.

thanks you !
