### ISSUE TITLE
directml on custom tensoflow build ?

### ISSUE THREAD

**Issue by Akash7789** [microsoft/tensorflow-directml#381]
Is custom tensorflow-directml build possible for tensorflow 2.3.0. If yes, what directml files or libraries would be required.

**Comment by PatriceVignola** [comment]
Hey @Akash7789 , `tensorflow-directml` is not possible for tensorflow 2.3.0, but we recently released a preview for `tensorflow-directml-plugin`, which should work with `tensorflow-cpu >= 2.9`. If you're interested, you can try it out:

```sh
pip install tensorflow-cpu
pip install tensorflow-directml-plugin
```

PyPi link: https://pypi.org/project/tensorflow-directml-plugin/
GitHub link: https://github.com/microsoft/tensorflow-directml-plugin

If you have any problems, don't hesitate to open an issue on the [issues page](https://github.com/microsoft/tensorflow-directml-plugin/issues)!
