### ISSUE TITLE
unbox expects Dml at::Tensor as inputs

### ISSUE THREAD

**Issue by mengdalida** [microsoft/tensorflow-directml#404]
RuntimeError: tensor.device().type() == at::DeviceType::PrivateUse1 INTERNAL ASSERT FAILED at "D:\\a\\_work\\2\\s\\pytorch-directml-plugin\\torch_directml\\csrc\\dml\\DMLTensor.cpp":31, please report a bug to PyTorch. unbox expects Dml at::Tensor as inputs

 my code is

  s1 = einsum('b i d, b j d -> b i j', q[:, i:end].cpu(), k.cpu())

**Comment by maggie1059** [comment]
Hi @mengdalida, it looks like you're using the `torch-directml` plugin. For PyTorch-DirectML issues, please open an issue on the [DirectML GitHub](https://github.com/microsoft/DirectML/issues).
