### ISSUE TITLE
Huge performance difference between onnxruntime and tensorflow-directml runtime

### ISSUE THREAD

**Issue by Coderx7** [microsoft/tensorflow-directml#87]
# System Information

Knowing your system configuration can help us diagnose issues more easily, so please provide as much information as possible. At a minimum, it is useful to know the following:

- Windows 10 Build/Version : Version 1909 / Build 18363.1139
- WSL distribution and its WSL version if testing Linux package (e.g. Ubuntu 20.04 WSL2)
- Python Version 3.7.4
- TensorFlow-DirectML Version: 1.15.3.dev200911
- Graphics card driver version (Intel Iris 580 Pro -27.20.100.8682)

`print_system_info.py` was not found!

```
Host System
--------------------------------------------------------------------------------
Windows 10 Version  : Windows 10 Enterprise 64-bit (10.0, Build 18363.1139)
Processor           : Intel(R) Core(TM) i7-6700HQ CPU @ 2.60GHz (1 CPUs)
Memory              : 16GB RAM
DirectX Version     : DirectX 12
```
# Repro Details

**Describe the current behavior**
When a converted tensorflow model (`'.pb`) is used to run inference on the latest version of tensorflow-directml, the inference time is several times worse than the onnx runtime execution time in cpu. i.e. it takes 1.2 seconds on GPU, while in onnxruntime its just aroun 30ms for CPU mode. changing the tensorflow code to run on CPU doesnt change anytihng and I'd still get 1.2/1.3 seconds.  

**Describe the expected behavior**
It should run much faster, at the very least it should match the onnx cpu stats.
 
**Code to reproduce the issue**
Provide a reproducible test case that is the bare minimum necessary to generate the problem.
This is the model : [simpnet_onnx_10312020.zip](https://github.com/microsoft/tensorflow-directml/files/5508007/simpnet_onnx_10312020.zip), and here is the code to reproduce this: 
```python
import tensorflow as tf
import numpy as np

from timeit import default_timer as timer
from tensorflow.python.client import device_lib 
import logging, os

logging.disable(logging.WARNING)
os.environ["TF_CPP_MIN_LOG_LEVEL"] = "3"
 
INPUT_TENSOR_NAME = 'input:0'
OUTPUT_TENSOR_NAME = 'add_13:0'
PB_PATH=r"D:\simpnet_onnx_10312020.pb"
 
print(device_lib.list_local_devices()) 
with tf.device("/device:DML:0"):
    img = np.random.randn(1,3,112,112)

    with tf.gfile.FastGFile(PB_PATH, 'rb') as f:
        graph_def = tf.GraphDef()
        graph_def.ParseFromString(f.read())
    
    with tf.Graph().as_default() as graph:
        tf.import_graph_def(graph_def, name="")
    
    input_tensor = graph.get_tensor_by_name(INPUT_TENSOR_NAME)
    output_tensor = graph.get_tensor_by_name(OUTPUT_TENSOR_NAME)

    with tf.Session(graph=graph) as sess:
        output_vals = sess.run(output_tensor, feed_dict={input_tensor: img})  #
    
    with tf.Session(graph=graph) as sess:
        start = timer()       
        output_vals = sess.run(output_tensor, feed_dict={input_tensor: img})  #
        end = timer()

    elapsed = end-start
    prediction=int(np.argmax(np.array(output_vals).squeeze(), axis=0))
    print(f'took {elapsed:.4f} sec or {elapsed*1000:.2f} ms')
```
results in : 
```
[name: "/device:CPU:0"
device_type: "CPU"
memory_limit: 268435456
locality {
}
incarnation: 10759035991921129072
, name: "/device:DML:0"
device_type: "DML"
memory_limit: 7678597939
locality {
}
incarnation: 11366947237963948902
physical_device_desc: "Intel(R) Iris(R) Pro Graphics 580"
]
took 1.2200 sec or 1220.03 ms
```

and the onnx model was converted like this : 
```python
import onnx
from onnx_tf.backend import prepare
onnx_model = onnx.load(r"D:\simpnet_onnx_10312020.onnx")
tf_rep = prepare(onnx_model)
tf_rep.export_graph(r"D:\simpnet_onnx_10312020.pb")
```
The original onnx model can be found here : [simpnet_onnx_10312020.zip ](https://github.com/microsoft/onnxruntime/files/5468826/simpnet_onnx_10312020.zip)

**Comment by jstoecker** [comment]
Thanks for the report! 

One thing to be careful with when profiling execution time is that the first run is going to be much slower. This is especially true with hardware backends like DML. I see that your code invokes `session.run` twice (presumably to "warm things up"), but the session is destroyed between invocations. If you run the model a few times without destroying the session you'll get much better numbers:

```
    with tf.Session(graph=graph) as sess:
        for i in range(1,10):
            start = timer()       
            output_vals = sess.run(output_tensor, feed_dict={input_tensor: img})  #
            end = timer()
            elapsed = end-start
            prediction=int(np.argmax(np.array(output_vals).squeeze(), axis=0))
            print(f'took {elapsed:.4f} sec or {elapsed*1000:.2f} ms')
```

On my machine (DirectML):
```
took 0.5327 sec or 532.68 ms
took 0.0049 sec or 4.88 ms
took 0.0031 sec or 3.07 ms
took 0.0031 sec or 3.09 ms
took 0.0030 sec or 3.05 ms
took 0.0030 sec or 2.98 ms
took 0.0031 sec or 3.13 ms
took 0.0030 sec or 2.97 ms
took 0.0029 sec or 2.92 ms
```
For comparison, the official tensorflow package (with CPU; I don't have CUDA installed at this very moment):
```
took 0.4818 sec or 481.79 ms
took 0.0064 sec or 6.40 ms
took 0.0065 sec or 6.48 ms
took 0.0063 sec or 6.35 ms
took 0.0067 sec or 6.66 ms
took 0.0065 sec or 6.46 ms
took 0.0064 sec or 6.37 ms
took 0.0064 sec or 6.40 ms
took 0.0064 sec or 6.37 ms
```

That said, we are going to be look at performance a lot more closely in the next few months. Our initial focus was functionality (mainly operators not implemented by DML device), and we still have quite a few kernels to write, but performance tuning always comes after that.

**Comment by Coderx7** [comment]
Thanks a lot really appreciate it
yes, I intended on doing that warm-up phase, but apparently I did it wrong. making everything run under the same session did it and it now works as expected. 
Really appreciate your answer and also eagerly looking forward to the next version. wish you the best of luck.
